[build]
command = "npm run build"
publish = "build/client"
functions = "netlify/functions"

[[functions]]
memory = 1024   # Augmente la mémoire allouée à chaque fonction à 1 Go
timeout = 60 

[dev]
command = "npm run dev"
framework = "vite"


# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/build/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Set immutable caching for images

[[headers]]
for = "/images/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Lighthouse plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
  output_path = "lighthouse-report.html"  
